import type { Metadata } from "next";
import {Inter, Roboto} from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navigation/navbar";
import {cn} from "@/lib/utils";
import {ThemeProvider} from "@/components/providers/theme-provider";
import { Toaster, toast } from 'sonner'

const roboto = Roboto({
    weight: ["400", "500", "700", "900"],
    subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {

  const isAdmin= false;
    console.log(process.env.GOOGLE_CLIENT_ID)
  return (
      <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex-grow px-6 md:px-12 mx-auto max-w-8xl">
      <Navbar/>
          <Toaster  />
      {children}
      {/*{isAdmin && profile}*/}

          </div>
      </ThemeProvider>
      </body>
    </html>
  );
}
