import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navigation/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
    profile
}: Readonly<{
  children: React.ReactNode;
  profile:React.ReactNode
}>) {

  const isAdmin= false;
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      {children}
      {/*{isAdmin && profile}*/}
      </body>
    </html>
  );
}
